### ISSUE TITLE
instagram queries always returns 0 followers

### ISSUE THREAD

**Issue by SaoYan** [spencerwooo/Substats#19]
```
https://api.spencerwoo.com/substats/?source=instagram&queryKey=spencer_wooo
```

Result:
```
{
  "status": 200,
  "data": {
    "totalSubs": 0,
    "subsInEachSource": {
      "instagram": 0
    },
    "failedSources": {
      "substats-error": {}
    }
  }
}
```

I tried with my ins id and some others, the API always returns 0 followers. The [handler code for instagram](https://github.com/spencerwooo/Substats/blob/master/src/utils/handlers/instagram.js) looks fine. Maybe there's something wrong with the backend. @spencerwooo

**Comment by SaoYan** [comment]
I found the problem: calling ```fetch()``` on endpoint ```https://www.instagram.com/${username}/?__a=1``` returns html rather than JSON. It seems that ```https://www.instagram.com/${username}/?__a=1``` is not a valid ins GraphQL API. In order to use ins api, an ins business account and a facebook developer account is required. See https://developers.facebook.com/docs/instagram-api/getting-started

**Comment by spencerwooo** [comment]
Hmmmm, this worked before, let me have a look.

**Comment by spencerwooo** [comment]
@SaoYan Could you try to deploy a second "Substats" on your Cloudflare Workers account and try if the Instagram path works? It seems that the current `api.spencerwoo.com` is limited by Instagram, because I can request the correct parameters through this (undocumented) API locally.. (Though I'm not sure.)

![image](https://user-images.githubusercontent.com/32114380/93730187-158a4380-fbfa-11ea-8a51-d0ed895d55ed.png)

**Comment by SaoYan** [comment]
https://www.instagram.com/${username}/?__a=1 is not supposed to be used, so I guess any domain that invokes it for some times will be banned.

**Comment by spencerwooo** [comment]
So the _rightful_ way to do this would be to get a verified dev account from instagram, and in order to do so I'm going to need a **business account**... All right I give up, dropping instagram support for now.

**Comment by spencerwooo** [comment]
This is weird, I rebuilt and published a version to Cloudflare Workers and the route is working again.

![image](https://user-images.githubusercontent.com/32114380/93971464-ccc1be80-fda2-11ea-8a61-9831bfbd2d9e.png)

Can you confirm @SaoYan? If so, I'm going to mark this route as unstable instead of inaccessible.

**Comment by spencerwooo** [comment]
Nope, never mind, still banned.
